// Reads the "Chula Qr Quest places" CSV export and generates a SQL seed file
// for the `checkpoints` table (game = 'csr'). Only db-relevant columns are kept:
// place names/descriptions live in the frontend, not this table (see games.schema.ts).
//
// Usage: bun scripts/generate-qr-quest-checkpoints-seed.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const CSV_PATH = join(
  import.meta.dir,
  "..",
  "[RPKM26] Chula Jigsaw Journey + Chula QR Quest Data & QR Code - Chula Qr Quest places.csv"
);
const OUT_PATH = join(import.meta.dir, "..", "seeds", "qr-quest-checkpoints.sql");

// RFC4180-ish CSV parser: handles quoted fields with embedded commas/newlines/"" escapes.
const parseCsv = (text: string): string[][] => {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];

    if (inQuotes) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
    } else if (char === ",") {
      row.push(field);
      field = "";
    } else if (char === "\n" || char === "\r") {
      if (char === "\r" && text[i + 1] === "\n") i++;
      row.push(field);
      field = "";
      if (row.some((cell) => cell !== "")) rows.push(row);
      row = [];
    } else {
      field += char;
    }
  }
  if (field !== "" || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
};

type CheckpointRow = {
  id: string;
  code: string;
  lat: number;
  lng: number;
  geofenceRadiusM: number;
};

const main = () => {
  const csvText = readFileSync(CSV_PATH, "utf-8");
  const [header, ...rows] = parseCsv(csvText);
  if (!header) throw new Error("empty CSV");

  const col = (name: string) => {
    const index = header.indexOf(name);
    if (index === -1) throw new Error(`missing column: ${name}`);
    return index;
  };

  const idIdx = col("id");
  const latIdx = col("lat");
  const lngIdx = col("lng");
  const radiusIdx = col("geofencingRadiusM");
  const pointCodeIdx = col("pointCode");

  const checkpoints: CheckpointRow[] = rows.map((r) => ({
    id: r[idIdx]!.trim(),
    code: r[pointCodeIdx]!.trim(),
    lat: Number(r[latIdx]),
    lng: Number(r[lngIdx]),
    geofenceRadiusM: Number(r[radiusIdx])
  }));

  for (const c of checkpoints) {
    if (
      !c.id ||
      !c.code ||
      Number.isNaN(c.lat) ||
      Number.isNaN(c.lng) ||
      Number.isNaN(c.geofenceRadiusM)
    ) {
      throw new Error(`invalid row: ${JSON.stringify(c)}`);
    }
  }

  const values = checkpoints
    .map((c) => `  ('${c.id}', 'csr', '${c.code}', ${c.lat}, ${c.lng}, ${c.geofenceRadiusM})`)
    .join(",\n");

  const sql = `-- Chula QR Quest checkpoint seed. Sourced from "Chula Qr Quest places" CSV export.
-- id is kept stable (matches frontend references); code is the pointCode scanned from the QR payload.
-- Generated by scripts/generate-qr-quest-checkpoints-seed.ts — re-run instead of hand-editing.
INSERT INTO checkpoints (id, game, code, lat, lng, geofence_radius_m) VALUES
${values}
ON CONFLICT (id) DO UPDATE SET
  game = EXCLUDED.game,
  code = EXCLUDED.code,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  geofence_radius_m = EXCLUDED.geofence_radius_m;
`;

  writeFileSync(OUT_PATH, sql);
  console.log(`wrote ${checkpoints.length} checkpoints to ${OUT_PATH}`);
};

main();
